words = ["babayım", "meşhuroe", "seray", "muhittin", "ömer", "öykü", "geliştirici", "bilgisayar", 
         "programlama", "algoritma", "mimar", "mimarlık", "matematik", "fizik", "kimya", 
         "biyoloji", "felsefe", "tarih", "coğrafya", "edebiyat", "sanatçı", "resim", 
         "heykel", "müzik", "piyano", "gitar", "keman", "flüt", "davul", "güneş", 
         "ayakkabı", "yıldız", "galaksi", "evren", "dünya", "atmosfer", "bulut", 
         "yağmur", "kar", "fırtına", "deniz", "okyanus", "göl", "nehir", "orman", 
         "dağ", "tepe", "vadi", "çöl", "kutuphane", "kitap", "dergi", "gazete", 
         "makale", "yazar", "şair", "roman", "şiir", "hikaye", "masal", "efsane", 
         "hayvan", "köpek", "kedi", "kuş", "balık", "tavşan", "aslan", "kaplan", 
         "ayı", "fil", "zürafa", "at", "koyun", "keçi", "inek", "tavuk", 
         "yumurta", "ekmek", "peynir", "zeytin", "domates", "salata", "biber", 
         "patates", "soğan", "sarımsak", "havuç", "elma", "armut", "muz", "çilek", 
         "kiraz", "vişne", "şeftali", "kayısı", "üzüm", "nar", "portakal", "limon", 
         "mandarins", "yemek", "içecek", "su", "kahve", "çay", "süt", "ayran", 
         "gazoz", "meyvesuyu", "otomobil", "bisiklet", "tren", "uçak", "gemi", 
         "otobüs", "taksi", "metro", "vapur", "helikopter"]